app:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    jdbc-url: jdbc:postgresql://localhost:5432/hotel_db
    username: postgres
    password: password
    pool-size: 30
    driverClassName: org.postgresql.Driver